# For GitHub use

apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL215dXNlcjpteXBhc3N3b3JkQG1vbmdvOjI3MDE3L21pY3Jvc2VydmljZXM/YXV0aFNvdXJjZT1hZG1pbg==
  JWT_SECRET: c2VjcmV0a2V5
  BASIC_AUTH_USER: YWRtaW4=
  BASIC_AUTH_PASS: MTIzNA==
