apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-profile
  template:
    metadata:
      labels:
        app: ms-profile
    spec:
      containers:
      - name: ms-profile
        image: ms-profile
        imagePullPolicy: Never
        ports:
        - containerPort: 4001
        envFrom:
        - secretRef:
            name: mongo-credentials
